# aws variables
aws_region = "us-east-2"
# project tags
owner = "gretchen[dot]keppel[at]gmail[dot]com"
project_name = "tfdemo-pubpriec2"
repo = "https://github.com/grrretchen/demo.aws-vpc-ec2-public-private"
# label tags
namespace = "bhl"
environment = "ue2"
stage = "l"
